name: Docker mypydemo CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  Compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install python3 pip modules
      run: python3 -m pip install -r requirements.txt
    - name: Compile platform dependent binary
      run: pyinstaller http_serv.py --onefile --name mypydemo-${{ runner.os }} 
      #;ls -ld dist/mypydemo
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nikhilpagote/mypydemo-${{ runner.os }}:$(date +%s)
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Test the Docker image
    - name: Push the Docker image to Dockerhub Registry 
      
